import type { Metadata } from 'next';
import { Inter, Noto_Sans_KR, Jua, Montserrat } from 'next/font/google';
import './globals.css';
import AuthSession from './_component/AuthSession';

// const inter = Noto_Sans_KR({ subsets: ['latin'] });
const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthSession>{children}</AuthSession>
                <div id="modal-root" />
            </body>
        </html>
    );
}
