import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { Session } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children, session }: { children: React.ReactNode; session: Session }) {
    const REFRESH_AGE = 3600 * 24 * 20; // 20 days
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider session={session} refetchInterval={REFRESH_AGE}>
                    {children}
                </SessionProvider>
            </body>
        </html>
    );
}
